-
  branches:
    only:
    - nuget
  
  image: Visual Studio 2017
  
  before_build:
    - nuget restore JDI.Light/JDI.Light.sln

  build_script: 
    - msbuild JDI.Light/JDI.Light.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - nuget pack "JDI.Light/JDI.Light.csproj" -Prop Configuration=Release

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: <ADD_HERE_BEFORE_PUBLISH>
    skip_symbols: false
    artifact: nupkg
 
  test:
    assemblies:
      - '**\*Tests.dll'
        
-
  branches:
    except:
    - nuget
  
  image: Visual Studio 2017
  
  environment:
    COVERALLS_REPO_TOKEN:
      secure: Lc7yX8JRxQdRZ8yYUPMuxrp22UkAIXLlkQK6H890Sh1GASFiKG4GkjwqbM9zy9O6
    
  before_build:
    - nuget restore JDI.Light/JDI.Light.sln

  build_script: 
    - msbuild JDI.Light/JDI.Light.sln /p:Configuration=Release /t:Rebuild

  test_script:
  - ps: >-
      .\JDI.Light\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"..\..\..\JDI.Light\packages\NUnit.ConsoleRunner.3.9.0\tools\nunit3-console.exe" "-targetargs:""JDI.Light\JDI.Light.UnitTests\bin\$env:CONFIGURATION\JDI.Light.UnitTests.dll"" /noshadow /appveyor" -filter:"+[*]*" -output:opencoverCoverage.xml

      $coveralls = (Resolve-Path "JDI.Light/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
